export type Locale = "en" | "vi";

const en = {
  nav: {
    links: [
      ["Services", "#services"],
      ["Process", "#process"],
      ["Deliverables", "#deliverables"],
      ["Ethics", "#ethics"],
      ["Packages", "#packages"],
    ],
    descriptor: "research data studio",
    cta: "Free feasibility check",
    open: "Open navigation",
    close: "Close navigation",
    language: "Change language",
    skip: "Skip to main content",
    primaryLabel: "Primary navigation",
    footerLabel: "Footer navigation",
  },
  hero: {
    titleLead: "Research-ready datasets",
    titleAccent: "for thesis and academic research",
    description: "Clean, documented, reproducible datasets for literature reviews, bibliometric studies, public web research, and thesis projects.",
    primary: "Check data feasibility",
    secondary: "View sample review",
  },
  sourcesBand: {
    eyebrow: "Common open and permitted sources",
    title: "Built around research-ready, documented source workflows",
    sources: ["OpenAlex", "Crossref", "PubMed", "arXiv", "DataCite", "DOAJ", "CORE", "Public Web"],
    note: "Source availability depends on access rules, permissions, and project scope.",
  },
  problem: {
    eyebrow: "Research data problem",
    title: "Raw data is not research-ready",
    description: "Research datasets need more than extraction. Sources must be checked, records cleaned, fields documented, and the workflow made reproducible.",
    items: [
      ["Messy sources", "Research data is often scattered across websites, APIs, spreadsheets, PDFs, repositories, and public databases."],
      ["Unclear feasibility", "Before collection begins, you need to know whether a source is accessible, permitted, useful, and stable."],
      ["Cleaning takes time", "Duplicates, missing values, inconsistent fields, encoding issues, and messy exports can stall the project."],
      ["Methodology matters", "For thesis and publication work, reviewers may ask how the dataset was collected, cleaned, and documented."],
    ],
  },
  workflow: {
    eyebrow: "Research workflow",
    title: "Scope first. Collect with confidence.",
    description: "Start with source feasibility, validate a small sample, then move to a full research-ready dataset.",
    state: "Before collection",
    stateValue: "Scope the project before collecting data",
    required: "Required first step",
    steps: [
      ["01", "Submit your research topic", "Tell us your topic, target data, preferred sources, expected fields, estimated size, and deadline."],
      ["02", "Feasibility check", "We review source availability, access options, data quality, limitations, and possible ethics or source risks."],
      ["03", "Sample dataset", "You receive a small sample dataset to validate structure, fields, quality, and usefulness."],
      ["04", "Final delivery", "You receive cleaned data, source logs, documentation, and reproducible scripts when included in scope."],
    ],
  },
  sampleReport: {
    reportLabel: "Feasibility report",
    statusLabel: "Reviewed before collection",
    eyebrow: "Sample review",
    title: "A feasibility check before collection begins",
    description: "Before collecting data, we map available sources, expected fields, access risks, and recommended deliverables.",
    topic: { label: "Research topic", value: "AI adoption in higher education" },
    sources: { label: "Recommended sources", value: "OpenAlex · Crossref · ERIC · Public university pages" },
    fields: { label: "Available fields", value: "title · abstract · DOI · authors · year · journal · keywords" },
    notes: { label: "Access notes", value: "Prefer open, API-accessible, and client-authorized sources" },
    risks: { label: "Risks to avoid", value: "Google Scholar scraping · paywalled full text without authorization · sensitive personal data" },
    output: { label: "Suggested output", value: "cleaned_dataset.csv · data_dictionary.xlsx · methodology_note.pdf" },
    cta: "Request your feasibility check",
    badges: ["Open / API sources", "Access risks flagged"],
  },
  useCases: {
    eyebrow: "Applications",
    title: "Built for real research workflows",
    description: "Common academic data projects we help scope, collect, clean, and document.",
    items: [
      { label: "Literature review", title: "Literature Review Dataset", description: "Collect paper metadata such as title, authors, DOI, abstract, year, journal, keywords, and source links.", fields: ["DOI", "abstract", "authors", "year", "journal"], bestFor: "SLR, scoping review, thesis background" },
      { label: "Bibliometric analysis", title: "Bibliometric Dataset", description: "Prepare publication data for trend analysis, citation mapping, co-author networks, institutions, and topic exploration.", fields: ["citations", "authors", "affiliations", "topics"], bestFor: "trends, networks, publication mapping" },
      { label: "Public web research", title: "Public Web Dataset", description: "Collect structured records from public job postings, policy pages, university programs, listings, or news metadata.", fields: ["URL", "category", "date", "record ID"], bestFor: "policy, jobs, education, public listings" },
      { label: "Dataset preparation", title: "Dataset Cleaning", description: "Clean and standardize existing CSV, Excel, JSON, or exported research files for analysis and reporting.", fields: ["deduplicate", "normalize", "validate", "document"], bestFor: "messy CSV and Excel exports" },
    ],
  },
  deliverables: {
    eyebrow: "Deliverables",
    title: "Research-ready deliverables",
    description: "Every project is delivered with structured files, documentation, and source notes so the dataset is easier to inspect, analyze, and explain.",
    badge: "Included in delivery",
    packageLabel: "Delivery package",
    packageSummary: "Raw files · Cleaned dataset · Documentation · Reproducible workflow",
    items: [
      ["raw_data.json", "Original collected records where applicable."],
      ["cleaned_dataset.csv", "Analysis-ready structured dataset."],
      ["data_dictionary.xlsx", "Explanation of fields, formats, and values."],
      ["source_log.csv", "Source URLs, API endpoints, access dates, and collection notes."],
      ["methodology_note.pdf", "Plain-language explanation of the collection and cleaning workflow."],
      ["reproducible_script.py", "Python script or notebook for a repeatable workflow."],
      ["README.md", "Project overview, file descriptions, and usage notes."],
    ],
  },
  standards: {
    eyebrow: "How we’re different",
    title: "Research-ready data is more than extraction",
    description: "Every project is scoped around access, documentation, and analysis needs.",
    items: [
      ["01", "Feasibility before collection", "Check source access, fields, risks, and limitations before committing to a full dataset."],
      ["02", "Documented by default", "Receive source notes, field definitions, and a clear record of what was collected."],
      ["03", "Ethics-aware source access", "Use public, permitted, open, API-accessible, or client-authorized sources."],
      ["04", "Reproducible handoff", "Add scripts, notebooks, or methodology notes when the research workflow requires them."],
    ],
  },
  ethics: {
    accessLabel: "Access protocol",
    protocol: "Source access review",
    eyebrow: "Ethics & source access",
    title: "Ethics-aware data collection",
    description: "We work with public, permitted, API-accessible, open, or client-authorized data sources. We do not bypass paywalls, scrape private accounts, or collect sensitive personal data without proper authorization and ethics clearance.",
    note: "We flag source and access risks early. Researchers remain responsible for any institutional ethics approval required by their project.",
    methodologyNote: "Each project can include a short methodology note describing collection scope, source access, cleaning steps, and known limitations.",
    safeguards: "Collection safeguards",
    reviewed: "Reviewed before collection",
    items: ["No paywall bypassing", "No private account scraping", "No unauthorized sensitive personal data collection", "Respect source limitations and access rules", "Source logs and methodology notes included", "Client authorization required for restricted sources"],
    logs: [["Logged", "Access basis"], ["Recorded", "Access date"], ["Included", "Source notes"]],
  },
  packages: {
    eyebrow: "Service packages",
    title: "Choose the right starting point",
    description: "Begin with feasibility, review a sample, then decide whether a full dataset project makes sense.",
    note: "Project-based pricing after feasibility review. Start with a free feasibility check before any paid work.",
    projectBased: "Project-based",
    items: [
      { title: "Data Feasibility Check", label: "Best first step", description: "A quick review of your topic, target data, possible sources, risks, and expected fields.", items: ["Source availability review", "Field feasibility", "Risk notes", "Suggested next step"], cta: "Request feasibility check" },
      { title: "Sample Dataset", description: "A small sample dataset to validate structure, quality, and usefulness before full collection.", items: ["50–200 sample records", "Initial schema", "Source notes", "Quality observations"], cta: "Request sample dataset" },
      { title: "Full Research Dataset", label: "Most complete", description: "A complete research-ready dataset with cleaning, documentation, and optional reproducible scripts.", items: ["Raw data where applicable", "Cleaned dataset", "Data dictionary", "Source log", "Methodology note", "Optional Python script/notebook"], cta: "Discuss full dataset", featured: true },
      { title: "Dataset Cleaning", description: "For researchers who already have messy files and need them cleaned, standardized, and documented.", items: ["CSV/Excel cleaning", "Deduplication", "Field normalization", "Data dictionary", "Clean export"], cta: "Clean existing dataset" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Practical details before you start",
    description: "Clear boundaries help determine whether a source and workflow fit your research project.",
    checks: "Feasibility review checks",
    checkItems: ["Source access", "Field coverage", "Ethics risk", "Expected limitations"],
    items: [
      ["Is this only web scraping?", "No. We focus on research-ready datasets. Depending on the project, the work may include source feasibility, API extraction, public web collection, data cleaning, documentation, and reproducible scripts."],
      ["Can you collect Google Scholar data?", "We avoid restricted or high-risk sources when access, terms, or ethics are unclear. We prefer permitted, open, API-accessible, or client-authorized sources."],
      ["Do you collect full-text papers?", "Only when the source is open, permitted, or the client has proper authorization. We do not bypass paywalls."],
      ["What files do I receive?", "Depending on scope, deliverables may include raw data, cleaned dataset, data dictionary, source log, methodology note, README, and reproducible script or notebook."],
      ["Can you clean data I already have?", "Yes. We can clean, deduplicate, normalize, and document existing CSV, Excel, JSON, or exported research files."],
    ],
  },
  finalCta: {
    eyebrow: "Free feasibility check",
    title: "Tell us what data you need",
    description: "Send your research topic, target sources, and expected output. We’ll review feasibility, risks, fields, and the best next step.",
    send: "Send details",
    items: ["Research topic", "Target fields", "Preferred sources", "Expected deadline"],
    button: "Request a free feasibility check",
    note: "No commitment. We review the source before collection.",
  },
  footer: { tagline: "Research-ready data collection & cleaning", rights: "© 2026 Research Data Lab. All rights reserved." },
};

const vi: typeof en = {
  nav: {
    links: [["Quy trình", "#process"], ["Ứng dụng", "#services"], ["Bàn giao", "#deliverables"], ["Đạo đức", "#ethics"], ["Gói dịch vụ", "#packages"]],
    descriptor: "hệ thống dữ liệu nghiên cứu",
    cta: "Kiểm tra tính khả thi miễn phí",
    open: "Mở menu điều hướng",
    close: "Đóng menu điều hướng",
    language: "Chuyển ngôn ngữ",
    skip: "Chuyển đến nội dung chính",
    primaryLabel: "Điều hướng chính",
    footerLabel: "Điều hướng chân trang",
  },
  hero: {
    titleLead: "Bộ dữ liệu sẵn sàng cho nghiên cứu",
    titleAccent: "cho luận văn và nghiên cứu học thuật",
    description: "Dữ liệu sạch, có tài liệu và có thể tái lập cho luận văn và dự án nghiên cứu.",
    primary: "Kiểm tra tính khả thi",
    secondary: "Xem mẫu đánh giá",
  },
  sourcesBand: {
    eyebrow: "Nguồn mở và nguồn được phép thường dùng",
    title: "Quy trình nguồn được lập tài liệu và chuẩn bị cho nghiên cứu",
    sources: ["OpenAlex", "Crossref", "PubMed", "arXiv", "DataCite", "DOAJ", "CORE", "Web công khai"],
    note: "Khả năng sử dụng nguồn phụ thuộc vào quy tắc truy cập, quyền hạn và phạm vi dự án.",
  },
  problem: {
    eyebrow: "Khoảng trống dữ liệu nghiên cứu",
    title: "Dữ liệu thô là chưa đủ cho nghiên cứu nghiêm túc",
    description: "Tìm dữ liệu thường khó hơn viết phần phân tích. Nguồn dữ liệu thiếu nhất quán, API khó sử dụng, và các bản ghi thu thập được vẫn cần làm sạch, lập tài liệu và xây dựng quy trình tái lập.",
    items: [
      ["Nguồn dữ liệu lộn xộn", "Dữ liệu nghiên cứu thường phân tán trên website, API, bảng tính, PDF, kho lưu trữ và cơ sở dữ liệu công khai."],
      ["Tính khả thi chưa rõ", "Trước khi thu thập, cần xác định nguồn có thể truy cập, được phép sử dụng, hữu ích và đủ ổn định hay không."],
      ["Làm sạch tốn thời gian", "Bản ghi trùng lặp, giá trị thiếu, trường không đồng nhất, lỗi mã hóa và tệp xuất lộn xộn có thể làm chậm toàn bộ dự án."],
      ["Phương pháp phải giải trình được", "Với luận văn và công bố khoa học, người phản biện có thể yêu cầu giải thích cách dữ liệu được thu thập, làm sạch và ghi chép."],
    ],
  },
  workflow: {
    eyebrow: "Quy trình nghiên cứu",
    title: "Cấu hình một lần. Thu thập có cơ sở.",
    description: "Bắt đầu bằng đánh giá khả thi, kiểm chứng trên một mẫu nhỏ, sau đó mới triển khai bộ dữ liệu nghiên cứu đầy đủ.",
    state: "Trước khi thu thập",
    stateValue: "Chốt phạm vi dự án trước khi thu thập dữ liệu",
    required: "Bước đầu bắt buộc",
    steps: [
      ["01", "Gửi chủ đề nghiên cứu", "Cho chúng tôi biết chủ đề, dữ liệu mục tiêu, nguồn ưu tiên, các trường cần có, quy mô dự kiến và thời hạn."],
      ["02", "Đánh giá tính khả thi", "Chúng tôi xem xét nguồn, phương án truy cập, chất lượng dữ liệu, giới hạn và các rủi ro về đạo đức hoặc điều khoản nguồn."],
      ["03", "Bộ dữ liệu mẫu", "Bạn nhận một mẫu nhỏ để kiểm tra cấu trúc, trường dữ liệu, chất lượng và mức độ phù hợp."],
      ["04", "Bàn giao cuối", "Bạn nhận dữ liệu đã làm sạch, nhật ký nguồn, tài liệu và mã tái lập nếu nằm trong phạm vi dự án."],
    ],
  },
  sampleReport: {
    reportLabel: "Báo cáo khả thi",
    statusLabel: "Đánh giá trước khi thu thập",
    eyebrow: "Mẫu đánh giá",
    title: "Kiểm tra tính khả thi trước khi thu thập",
    description: "Trước khi thu thập dữ liệu, chúng tôi lập bản đồ các nguồn có sẵn, các trường dự kiến, rủi ro truy cập và đề xuất đầu ra.",
    topic: { label: "Chủ đề nghiên cứu", value: "Áp dụng AI trong giáo dục đại học" },
    sources: { label: "Nguồn đề xuất", value: "OpenAlex · Crossref · ERIC · Trang web trường đại học công" },
    fields: { label: "Trường dữ liệu có sẵn", value: "title · abstract · DOI · authors · year · journal · keywords" },
    notes: { label: "Ghi chú truy cập", value: "Ưu tiên các nguồn mở, có API và được sự cho phép của khách hàng" },
    risks: { label: "Rủi ro cần tránh", value: "Cào dữ liệu Google Scholar · tải toàn văn bài báo có bản quyền trái phép · dữ liệu cá nhân nhạy cảm" },
    output: { label: "Đầu ra đề xuất", value: "cleaned_dataset.csv · data_dictionary.xlsx · methodology_note.pdf" },
    cta: "Yêu cầu đánh giá khả thi",
    badges: ["Nguồn mở / API", "Đã ghi nhận rủi ro"],
  },
  useCases: {
    eyebrow: "Ứng dụng",
    title: "Được thiết kế cho quy trình nghiên cứu thực tế",
    description: "Các dạng dự án dữ liệu học thuật phổ biến mà chúng tôi hỗ trợ, được xác định theo câu hỏi phân tích của nghiên cứu.",
    items: [
      { label: "Tổng quan tài liệu", title: "Dữ liệu tổng quan tài liệu", description: "Thu thập siêu dữ liệu bài báo như tiêu đề, tác giả, DOI, tóm tắt, năm, tạp chí, từ khóa và liên kết nguồn.", fields: ["DOI", "tóm tắt", "tác giả", "năm", "tạp chí"], bestFor: "SLR, scoping review, nền tảng luận văn" },
      { label: "Phân tích trắc lượng", title: "Dữ liệu trắc lượng thư mục", description: "Chuẩn bị dữ liệu công bố cho phân tích xu hướng, bản đồ trích dẫn, mạng lưới đồng tác giả, tổ chức và chủ đề.", fields: ["trích dẫn", "tác giả", "đơn vị", "chủ đề"], bestFor: "xu hướng, mạng lưới, bản đồ công bố" },
      { label: "Nghiên cứu web công khai", title: "Dữ liệu web công khai", description: "Thu thập bản ghi có cấu trúc từ tin tuyển dụng, trang chính sách, chương trình đại học, danh mục công khai hoặc siêu dữ liệu tin tức.", fields: ["URL", "phân loại", "ngày", "mã bản ghi"], bestFor: "chính sách, việc làm, giáo dục, danh mục công" },
      { label: "Chuẩn bị dữ liệu", title: "Làm sạch dữ liệu", description: "Làm sạch và chuẩn hóa tệp CSV, Excel, JSON hoặc dữ liệu xuất sẵn để phục vụ phân tích và báo cáo.", fields: ["khử trùng", "chuẩn hóa", "kiểm tra", "lập tài liệu"], bestFor: "tệp CSV và Excel lộn xộn" },
    ],
  },
  deliverables: {
    eyebrow: "Danh mục bàn giao",
    title: "Bạn sẽ nhận được gì",
    description: "Mỗi bộ dữ liệu đi kèm các tệp giúp quy trình dễ kiểm tra, phân tích và giải trình hơn.",
    badge: "Bao gồm khi bàn giao",
    packageLabel: "Gói bàn giao",
    packageSummary: "Tệp thô · Dữ liệu sạch · Tài liệu · Quy trình tái lập",
    items: [
      ["raw_data.json", "Bản ghi gốc đã thu thập khi phù hợp."],
      ["cleaned_dataset.csv", "Bộ dữ liệu có cấu trúc, sẵn sàng phân tích."],
      ["data_dictionary.xlsx", "Giải thích các trường, định dạng và giá trị."],
      ["source_log.csv", "URL nguồn, endpoint API, ngày truy cập và ghi chú thu thập."],
      ["methodology_note.pdf", "Giải thích dễ hiểu về quy trình thu thập và làm sạch."],
      ["reproducible_script.py", "Mã Python hoặc notebook để tái lập quy trình."],
      ["README.md", "Tổng quan dự án, mô tả tệp và hướng dẫn sử dụng."],
    ],
  },
  standards: {
    eyebrow: "Điểm khác biệt",
    title: "Dữ liệu sẵn sàng cho nghiên cứu không chỉ là trích xuất",
    description: "Mỗi dự án được xác định theo quyền truy cập, yêu cầu tài liệu và nhu cầu phân tích.",
    items: [
      ["01", "Đánh giá trước khi thu thập", "Kiểm tra nguồn, trường dữ liệu, rủi ro và giới hạn trước khi triển khai toàn bộ."],
      ["02", "Mặc định có tài liệu", "Nhận ghi chú nguồn, định nghĩa trường và hồ sơ rõ ràng về dữ liệu đã thu thập."],
      ["03", "Truy cập nguồn có cân nhắc đạo đức", "Sử dụng nguồn công khai, được phép, nguồn mở, có API hoặc được khách hàng ủy quyền."],
      ["04", "Bàn giao có thể tái lập", "Kèm mã, notebook hoặc ghi chú phương pháp khi quy trình nghiên cứu yêu cầu."],
    ],
  },
  ethics: {
    accessLabel: "Giao thức truy cập",
    protocol: "Đánh giá quyền truy cập nguồn",
    eyebrow: "Giao thức truy cập và đạo đức",
    title: "Thu thập dữ liệu có cân nhắc đạo đức",
    description: "Chúng tôi chỉ làm việc với nguồn công khai, được phép, có API, nguồn mở hoặc được khách hàng ủy quyền. Chúng tôi không vượt tường phí, thu thập từ tài khoản riêng tư hay lấy dữ liệu cá nhân nhạy cảm khi chưa có ủy quyền và phê duyệt đạo đức phù hợp.",
    note: "Chúng tôi cảnh báo rủi ro về nguồn và quyền truy cập. Nhà nghiên cứu vẫn chịu trách nhiệm về các phê duyệt của tổ chức hoặc hội đồng đạo đức mà dự án yêu cầu.",
    methodologyNote: "Mỗi dự án có thể bao gồm một ghi chú phương pháp ngắn mô tả phạm vi thu thập, quyền truy cập nguồn, các bước làm sạch và những giới hạn đã biết.",
    safeguards: "Biện pháp kiểm soát",
    reviewed: "Đánh giá trước khi thu thập",
    items: ["Không vượt tường phí", "Không thu thập từ tài khoản riêng tư", "Không thu thập trái phép dữ liệu cá nhân nhạy cảm", "Tôn trọng giới hạn và quy tắc truy cập của nguồn", "Kèm nhật ký nguồn và ghi chú phương pháp", "Nguồn hạn chế cần có ủy quyền của khách hàng"],
    logs: [["Đã ghi", "Cơ sở truy cập"], ["Đã lưu", "Ngày truy cập"], ["Có kèm", "Ghi chú nguồn"]],
  },
  packages: {
    eyebrow: "Gói dịch vụ",
    title: "Bắt đầu với mức hỗ trợ phù hợp",
    description: "Bắt đầu từ đánh giá khả thi, kiểm chứng bằng mẫu, sau đó quyết định dự án dữ liệu đầy đủ có phù hợp hay không.",
    note: "Chi phí được xác định theo dự án sau bước đánh giá khả thi. Hãy bắt đầu bằng đánh giá miễn phí trước khi thực hiện bất kỳ công việc có phí nào.",
    projectBased: "Theo từng dự án",
    items: [
      { title: "Đánh giá tính khả thi", label: "Bước đầu phù hợp nhất", description: "Đánh giá nhanh chủ đề, dữ liệu mục tiêu, nguồn tiềm năng, rủi ro và các trường dự kiến.", items: ["Đánh giá nguồn sẵn có", "Tính khả thi của trường dữ liệu", "Ghi chú rủi ro", "Đề xuất bước tiếp theo"], cta: "Yêu cầu đánh giá miễn phí" },
      { title: "Bộ dữ liệu mẫu", description: "Một mẫu nhỏ để kiểm tra cấu trúc, chất lượng và mức độ hữu ích trước khi thu thập đầy đủ.", items: ["50–200 bản ghi mẫu", "Schema ban đầu", "Ghi chú nguồn", "Nhận xét chất lượng"], cta: "Yêu cầu dữ liệu mẫu" },
      { title: "Bộ dữ liệu nghiên cứu đầy đủ", label: "Đầy đủ nhất", description: "Bộ dữ liệu sẵn sàng cho nghiên cứu với làm sạch, tài liệu và mã tái lập tùy chọn.", items: ["Dữ liệu thô khi phù hợp", "Dữ liệu đã làm sạch", "Từ điển dữ liệu", "Nhật ký nguồn", "Ghi chú phương pháp", "Mã Python/notebook tùy chọn"], cta: "Trao đổi dự án", featured: true },
      { title: "Chỉ làm sạch dữ liệu", description: "Dành cho nhà nghiên cứu đã có tệp dữ liệu lộn xộn và cần làm sạch, chuẩn hóa, lập tài liệu.", items: ["Làm sạch CSV/Excel", "Khử trùng lặp", "Chuẩn hóa trường", "Từ điển dữ liệu", "Tệp xuất sạch"], cta: "Làm sạch dữ liệu của tôi" },
    ],
  },
  faq: {
    eyebrow: "Câu hỏi thường gặp",
    title: "Thông tin thực tế trước khi bắt đầu",
    description: "Ranh giới rõ ràng giúp xác định nguồn và quy trình có phù hợp với dự án nghiên cứu hay không.",
    checks: "Nội dung đánh giá khả thi",
    checkItems: ["Quyền truy cập nguồn", "Độ phủ trường dữ liệu", "Rủi ro đạo đức", "Các giới hạn dự kiến"],
    items: [
      ["Dịch vụ này chỉ là web scraping?", "Không. Chúng tôi tập trung vào dữ liệu sẵn sàng cho nghiên cứu, có thể bao gồm đánh giá nguồn, trích xuất API, thu thập web công khai, làm sạch, lập tài liệu và mã tái lập."],
      ["Có thể thu thập dữ liệu Google Scholar không?", "Chúng tôi tránh các nguồn hạn chế hoặc rủi ro khi có vấn đề về truy cập, điều khoản hoặc đạo đức. Chúng tôi ưu tiên nguồn được phép, nguồn mở, có API hoặc được khách hàng ủy quyền."],
      ["Có thu thập toàn văn bài báo không?", "Chỉ khi nguồn mở, được phép hoặc khách hàng có ủy quyền phù hợp. Chúng tôi không vượt tường phí."],
      ["Tôi sẽ nhận những tệp nào?", "Tùy phạm vi, bàn giao có thể gồm dữ liệu thô, dữ liệu sạch, từ điển dữ liệu, nhật ký nguồn, ghi chú phương pháp, README và mã hoặc notebook tái lập."],
      ["Có thể làm sạch dữ liệu tôi đã có không?", "Có. Chúng tôi có thể làm sạch, khử trùng, chuẩn hóa và lập tài liệu cho tệp CSV, Excel, JSON hoặc dữ liệu xuất sẵn."],
    ],
  },
  finalCta: {
    eyebrow: "Đánh giá khả thi miễn phí",
    title: "Cho chúng tôi biết dữ liệu bạn cần",
    description: "Gửi chủ đề nghiên cứu, nguồn mục tiêu và đầu ra dự kiến. Chúng tôi sẽ đánh giá tính khả thi, rủi ro, các trường dữ liệu và bước tiếp theo phù hợp.",
    send: "Gửi các thông tin này",
    items: ["Chủ đề nghiên cứu", "Trường dữ liệu mục tiêu", "Nguồn ưu tiên", "Thời hạn dự kiến"],
    button: "Yêu cầu đánh giá khả thi miễn phí",
    note: "Không ràng buộc. Chúng tôi đánh giá nguồn trước khi thu thập.",
  },
  footer: { tagline: "Thu thập và làm sạch dữ liệu sẵn sàng cho nghiên cứu", rights: "© 2026 Research Data Lab. Bảo lưu mọi quyền." },
};

export const content = { en, vi };

export function getContent(locale: Locale) {
  return content[locale];
}
